config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # Homepage
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("rtmeli.users.urls", namespace="users")),
    # Custom routes
    path("accounts/", include("rtmeli.accounts.urls", namespace="accounts")),
    path("products/", include("rtmeli.products.urls", namespace="products")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

rtmeli/accounts/urls.py
from django.urls import path

from rtmeli.accounts.views import (
    login_view,
    logout_view,
    authorize_view,
    signout_view
)

app_name = "accounts"
urlpatterns = [
    path("login/", view=login_view, name="login"),
    path("logout/", view=logout_view, name="logout"),
    path("signout/", view=signout_view, name="signout"),
    path("authorize/", view=authorize_view, name="authorize"),
]

rtmeli/products/urls.py
from django.urls import path

from rtmeli.products.views import (
    top_prices_view,
    top_sellers_view,
)

app_name = "products"
urlpatterns = [
    path("top_prices/", view=top_prices_view, name="top_prices"),
    path("top_sellers/", view=top_sellers_view, name="top_sellers"),
]

rtmeli/users/urls.py
from django.urls import path

from rtmeli.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    profile_view
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("profile/", view=profile_view, name="profile"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

rtmeli/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

rtmeli/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

rtmeli/accounts/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, RedirectView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings

from ..api.services import MercadolibreApi

from accounts.services import (
    get_auth_url,
    get_access_token
)

from utils.decorators import login_required

class LoginView(TemplateView):
    def get(self,request):
        auth_url = get_auth_url()
        return render(request,'account/login.html',{'auth_url':auth_url})

login_view = LoginView.as_view()

class LogoutView(TemplateView):
    @method_decorator(login_required())
    def get(self,request):
        return render(request,'account/logout.html')

logout_view = LogoutView.as_view()

class SignoutView(RedirectView):
    @method_decorator(login_required())
    def get(self,request):
        #TODO: change logout behaviour to work with allauth
        del request.session['access_token']
        request.session.modified = True
        return HttpResponseRedirect(reverse('home'))

signout_view = SignoutView.as_view()

class AuthorizeView(TemplateView):
    def get(self,request):
        if(request.GET.get('code')):
            token = get_access_token(request.GET.get('code'))
        request.session['access_token'] = token
        request.session.modified = True
        return HttpResponseRedirect(reverse('home'))

authorize_view = AuthorizeView.as_view()

rtmeli/products/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from .services import (
    get_category_items_count,
    get_most_sold_seller_ids,
    get_top_items_by_price,
    get_users_nicknames
)

class TopSellersView(TemplateView):
    def get(self,request):
        category_id = "MLA420040"
        if (request.session.get('access_token',None)):
            token = request.session['access_token']
        total_items_category = get_category_items_count(category_id)
        seller_ids = get_most_sold_seller_ids(category_id, total_items_category)
        sellers = get_users_nicknames(seller_ids)
        return render(request,'pages/topsellers.html',{'items':sellers})

top_sellers_view = TopSellersView.as_view()

class TopPriceItemsView(TemplateView):
    def get(self,request):
        category_id = "MLA420040"
        limit = 10
        sort = 'price_desc'
        items_list = get_top_items_by_price(category_id, limit, sort)
        return render(request,'pages/topprices.html',{'items':items_list})

top_prices_view = TopPriceItemsView.as_view()

rtmeli/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, TemplateView

from .services import get_profile_from_meli
from ..utils.decorators import login_required

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class ProfileView(TemplateView):

    @method_decorator(login_required())
    def get(self,request):
        profile = get_profile_from_meli(request.session['access_token'])
        return render(request,'users/profile.html')

profile_view = ProfileView.as_view()

rtmeli/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Real Trends Test{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Real Trends Test</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'products:top_prices' %}">{% trans "Top Priced Items" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'products:top_sellers' %}">{% trans "Top Sellers" %}</a>
            </li>
            {% if not request.session.access_token %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login'  %}">{% trans "Sign In" %}</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout'  %}">{% trans "Sign Out" %}</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

    {% block content %}
    {% endblock %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

rtmeli/templates/pages/home.html
{% extends "base.html" %}
{% load static %}

{% load i18n %}

{% block content %}

    <h1>{% trans "Welcome to the Real Trends test - By" %} Guido Bonomini</h1>

{% endblock %}

rtmeli/templates/pages/topprices.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<h1>{% trans "Top 10 Priced Items" %}</h1>

<ul class="list-group">
    {% for item in items %}
    <li class="list-group-item">
        <h2>{{item.title}}</h2>
        <h4>Precio: {{item.price}}</h4>
        <a href="{{item.link}}">{{item.link}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

rtmeli/templates/pages/topsellers.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<h1>{% trans "Top 10 Sellers" %}</h1>

<ul class="list-group">
    {% for item in items %}
        <li class="list-group-item">
            {{item.nickname}}
        </li>
    {% endfor %}
</ul>
{% endblock %}

rtmeli/templates/users/profile.html
{% extends "base.html" %}
{% load i18n %}
<h1></h1>

rtmeli/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

rtmeli/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}